package com.example.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material.icons.filled.Shield
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.model.AiAnalysisResult
import com.example.model.PaperDuration
import com.example.model.TradeSignal
import com.example.ui.theme.AccentGold
import com.example.ui.theme.BearishRed
import com.example.ui.theme.BullishGreen
import com.example.ui.theme.DarkBg
import com.example.ui.theme.DarkBorder
import com.example.ui.theme.DarkSurface
import com.example.ui.theme.DarkSurfaceElevated
import com.example.ui.theme.NeonCyan
import com.example.ui.theme.TextMuted
import com.example.ui.theme.TextPrimary
import com.example.ui.theme.TextSecondary
import com.example.ui.theme.WarningAmber

@Composable
fun AiResultCard(
    result: AiAnalysisResult,
    selectedDuration: PaperDuration,
    onStartPaperTrade: () -> Unit,
    modifier: Modifier = Modifier
) {
    val isBuy = result.signal == TradeSignal.BUY
    val isSell = result.signal == TradeSignal.SELL

    val signalColor = when {
        isBuy -> BullishGreen
        isSell -> BearishRed
        else -> WarningAmber
    }

    val glowBorderBrush = Brush.horizontalGradient(
        listOf(
            signalColor.copy(alpha = 0.8f),
            NeonCyan.copy(alpha = 0.5f)
        )
    )

    Card(
        modifier = modifier
            .fillMaxWidth()
            .border(1.5.dp, glowBorderBrush, RoundedCornerShape(16.dp))
            .testTag("ai_result_card"),
        shape = RoundedCornerShape(16.dp),
        colors = CardDefaults.cardColors(containerColor = DarkSurface)
    ) {
        Column(
            modifier = Modifier
                .padding(18.dp)
        ) {
            // Header: MZK AI TRADING brand banner
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column {
                    Text(
                        text = "MZK AI TRADING",
                        fontSize = 17.sp,
                        fontWeight = FontWeight.Black,
                        letterSpacing = 1.2.sp,
                        color = NeonCyan
                    )
                    Text(
                        text = "Generated by ${result.providerUsed}",
                        fontSize = 11.sp,
                        color = TextMuted
                    )
                }

                // Confidence pill
                Box(
                    modifier = Modifier
                        .clip(RoundedCornerShape(8.dp))
                        .background(DarkSurfaceElevated)
                        .border(1.dp, signalColor.copy(alpha = 0.5f), RoundedCornerShape(8.dp))
                        .padding(horizontal = 10.dp, vertical = 5.dp)
                ) {
                    Text(
                        text = "CONFIDENCE: ${result.confidence}%",
                        color = signalColor,
                        fontWeight = FontWeight.Bold,
                        fontSize = 12.sp
                    )
                }
            }

            Spacer(modifier = Modifier.height(14.dp))

            // SYMBOL & TIMEFRAME
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(DarkSurfaceElevated, RoundedCornerShape(8.dp))
                    .padding(horizontal = 12.dp, vertical = 8.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = result.symbol,
                    fontSize = 16.sp,
                    fontWeight = FontWeight.Bold,
                    color = TextPrimary
                )
                Text(
                    text = "TIMEFRAME: ${result.timeframe.uppercase()}",
                    fontSize = 12.sp,
                    fontWeight = FontWeight.SemiBold,
                    color = TextSecondary
                )
            }

            Spacer(modifier = Modifier.height(14.dp))

            // SIGNAL & ACTION BANNER
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Column(
                    modifier = Modifier
                        .weight(1f)
                        .background(DarkSurfaceElevated, RoundedCornerShape(10.dp))
                        .padding(10.dp)
                ) {
                    Text(text = "SIGNAL", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = TextMuted)
                    Text(
                        text = result.signal.name,
                        fontSize = 20.sp,
                        fontWeight = FontWeight.Black,
                        color = signalColor
                    )
                }

                Column(
                    modifier = Modifier
                        .weight(1.5f)
                        .background(DarkSurfaceElevated, RoundedCornerShape(10.dp))
                        .padding(10.dp)
                ) {
                    Text(text = "ACTION", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = TextMuted)
                    Text(
                        text = result.action,
                        fontSize = 13.sp,
                        fontWeight = FontWeight.Bold,
                        color = TextPrimary
                    )
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // ENTRY, STOP LOSS, TAKE PROFIT (3 column financial box)
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(DarkBg, RoundedCornerShape(10.dp))
                    .border(1.dp, DarkBorder, RoundedCornerShape(10.dp))
                    .padding(12.dp),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Column {
                    Text(text = "ENTRY", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = TextMuted)
                    Spacer(modifier = Modifier.height(2.dp))
                    Text(
                        text = formatPrice(result.entry),
                        fontSize = 14.sp,
                        fontWeight = FontWeight.Bold,
                        color = TextPrimary
                    )
                }

                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Text(text = "STOP LOSS", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = BearishRed)
                    Spacer(modifier = Modifier.height(2.dp))
                    Text(
                        text = formatPrice(result.stopLoss),
                        fontSize = 14.sp,
                        fontWeight = FontWeight.Bold,
                        color = BearishRed
                    )
                }

                Column(horizontalAlignment = Alignment.End) {
                    Text(text = "TAKE PROFIT", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = BullishGreen)
                    Spacer(modifier = Modifier.height(2.dp))
                    Text(
                        text = formatPrice(result.takeProfit),
                        fontSize = 14.sp,
                        fontWeight = FontWeight.Bold,
                        color = BullishGreen
                    )
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // TREND & RISK LEVEL
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Box(
                    modifier = Modifier
                        .weight(1f)
                        .background(DarkSurfaceElevated, RoundedCornerShape(8.dp))
                        .padding(horizontal = 10.dp, vertical = 7.dp)
                ) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(text = "TREND: ", fontSize = 11.sp, color = TextMuted)
                        Text(
                            text = result.trend.name,
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            color = when (result.trend) {
                                com.example.model.MarketTrend.BULLISH -> BullishGreen
                                com.example.model.MarketTrend.BEARISH -> BearishRed
                                com.example.model.MarketTrend.NEUTRAL -> WarningAmber
                            }
                        )
                    }
                }

                Box(
                    modifier = Modifier
                        .weight(1f)
                        .background(DarkSurfaceElevated, RoundedCornerShape(8.dp))
                        .padding(horizontal = 10.dp, vertical = 7.dp)
                ) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(text = "RISK: ", fontSize = 11.sp, color = TextMuted)
                        Text(
                            text = result.risk.name,
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            color = when (result.risk) {
                                com.example.model.RiskLevel.LOW -> BullishGreen
                                com.example.model.RiskLevel.MEDIUM -> WarningAmber
                                com.example.model.RiskLevel.HIGH -> BearishRed
                            }
                        )
                    }
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // WHY SECTION
            Text(
                text = "WHY:",
                fontSize = 12.sp,
                fontWeight = FontWeight.Bold,
                color = TextSecondary
            )
            Spacer(modifier = Modifier.height(4.dp))
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(DarkSurfaceElevated, RoundedCornerShape(8.dp))
                    .padding(10.dp)
            ) {
                result.reasons.forEach { reason ->
                    Text(
                        text = "• $reason",
                        fontSize = 12.sp,
                        color = TextPrimary,
                        modifier = Modifier.padding(vertical = 2.dp)
                    )
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Compliance & Education Notice
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(DarkBg, RoundedCornerShape(6.dp))
                    .padding(8.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Icon(
                    imageVector = Icons.Default.Info,
                    contentDescription = null,
                    tint = TextMuted,
                    modifier = Modifier.padding(end = 6.dp)
                )
                Text(
                    text = "Paper-trading simulation only. Algorithmic confidence is NOT a guarantee of profit. Never connect to real money accounts.",
                    fontSize = 10.sp,
                    color = TextMuted,
                    lineHeight = 13.sp
                )
            }

            Spacer(modifier = Modifier.height(14.dp))

            // ACTION BUTTON: START PAPER TRADE
            Button(
                onClick = onStartPaperTrade,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(48.dp)
                    .testTag("start_paper_trade_button"),
                shape = RoundedCornerShape(10.dp),
                colors = ButtonDefaults.buttonColors(
                    containerColor = signalColor,
                    contentColor = DarkBg
                )
            ) {
                Icon(
                    imageVector = Icons.Default.PlayArrow,
                    contentDescription = null,
                    modifier = Modifier.padding(end = 6.dp)
                )
                Text(
                    text = "START PAPER TRADE (${selectedDuration.label})",
                    fontSize = 14.sp,
                    fontWeight = FontWeight.Bold
                )
            }
        }
    }
}

private fun formatPrice(price: Double): String {
    return when {
        price >= 1000.0 -> String.format("$%,.1f", price)
        price >= 1.0 -> String.format("$%.3f", price)
        else -> String.format("$%.5f", price)
    }
}
